import { useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { Classroom, CreateClassroomData, ClassroomType } from '@/types/classroom';
import { useToast } from '@/hooks/use-toast';

export const useClassrooms = () => {
  const { user } = useAuth();
  const { toast } = useToast();
  const [classrooms, setClassrooms] = useState<Classroom[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchClassrooms = async () => {
    if (!user) return;
    
    setLoading(true);
    const { data, error } = await supabase
      .from('classrooms')
      .select('*')
      .eq('teacher_id', user.id)
      .order('created_at', { ascending: false });

    if (error) {
      console.error('Error fetching classrooms:', error);
      toast({
        title: 'Error',
        description: 'Failed to load classrooms',
        variant: 'destructive',
      });
    } else {
      setClassrooms(data as unknown as Classroom[]);
    }
    setLoading(false);
  };

  const createClassroom = async (data: CreateClassroomData) => {
    if (!user) return { error: new Error('Not authenticated') };

    const { data: newClassroom, error } = await supabase
      .from('classrooms')
      .insert({
        teacher_id: user.id,
        name: data.name,
        description: data.description || null,
        subject: data.subject,
        classroom_type: data.classroom_type,
        monthly_fee: data.classroom_type === 'private' ? (data.monthly_fee || 0) : 0,
        max_students: data.max_students || 50,
        invite_code: '', // Will be auto-generated by trigger
      })
      .select()
      .single();

    if (error) {
      toast({
        title: 'Error',
        description: 'Failed to create classroom',
        variant: 'destructive',
      });
      return { error };
    }

    toast({
      title: 'Success',
      description: 'Classroom created successfully',
    });

    await fetchClassrooms();
    return { data: newClassroom as unknown as Classroom, error: null };
  };

  const deleteClassroom = async (classroomId: string) => {
    const { error } = await supabase
      .from('classrooms')
      .delete()
      .eq('id', classroomId);

    if (error) {
      toast({
        title: 'Error',
        description: 'Failed to delete classroom',
        variant: 'destructive',
      });
      return { error };
    }

    toast({
      title: 'Success',
      description: 'Classroom deleted successfully',
    });

    await fetchClassrooms();
    return { error: null };
  };

  const getStudentCount = async (classroomId: string) => {
    const { count, error } = await supabase
      .from('classroom_students')
      .select('*', { count: 'exact', head: true })
      .eq('classroom_id', classroomId)
      .eq('is_active', true);

    if (error) return 0;
    return count || 0;
  };

  useEffect(() => {
    fetchClassrooms();
  }, [user]);

  const schoolClassrooms = classrooms.filter(c => c.classroom_type === 'school');
  const privateClassrooms = classrooms.filter(c => c.classroom_type === 'private');

  return {
    classrooms,
    schoolClassrooms,
    privateClassrooms,
    loading,
    createClassroom,
    deleteClassroom,
    getStudentCount,
    refetch: fetchClassrooms,
  };
};
